### PR TITLE
docs: 📝 Posts on making a sitemap and rss feed

### LINKED ISSUE #1: Cannot access query on a page with prerendering enabled
Hey Matt!

I'm putting together a guide on adding an RSS feed using this template as reference and there's an error after installing dependencies and running the dev server.

Turning off the `  export const prerender = true` flag in `src/routes.svelte` resolves this.

I can make a PR for it if you like?

### PR DESCRIPTION
**Pull request by spences10**
Contribution posts to help users of the template make their own sitemap and RSS feeds.

fix: 🐛 remove prerender flag

Index page not loading without removing prerender

Closes #1

### CODE REVIEW

**Comment by mattjennings** [comment]
hey @spences10, I've finally gotten around to updating the template to fix the various errors we ran into.

I believe the only change that affects this PR is `src/lib/get-posts` - I ended up adding it to the template after reading your posts. It makes sense to have it there already. However it works slightly differently in that instead of returning just the metadata, it returns `{ metadata, component }`, so you'll want to update the post accordingly to do something like this for sitemap/rss:

```js
const posts = getPosts().map(post => post.metadata)
```

I also removed pagination for sake of keeping the template simple. While it was nice to have, keeping pagination on the index page while maintaining SSG support was problematic, so I just decided to get rid of it. I don't think this affects either of your posts though.

**Comment by spences10** [comment]
This is good to go now @mattjennings 

I'll wait for this to get merged in then there's another post on [making an email form submit with Revue] I'd like to contribute as well.

[making an email form submit with Revue]:https://scottspence.com/posts/email-form-submission-with-sveltekit

**Comment by mattjennings** [comment]
Looks good! I'll merge it in. 

I think for now I'll keep it to just these posts. While that post looks useful I'm not certain it's as relevant to this template as the sitemap/RSS ones are. But I do appreciate it!

**Comment by spences10** [comment]
Yeah, no worries, it is a very specific solution.

**Pull request merged**
